site_config.settings_form:
  path: '/admin/site-config'
  defaults:
    _title: 'Site Config Settings'
    _form: 'Drupal\site_config\Form\SettingsForm'
  requirements:
    _permission: 'administer site configuration'
